### ISSUE TITLE
`ta init` fails at auth token step

### ISSUE THREAD

**Issue by philnash** [twilio/autopilot-cli#19]
I installed the cli with

```
npm i -g @twilio/autopilot-cli
```

Then ran `ta init`. The program asked for my account sid, then my auth token. When I input my auth token and pressed return I received an error:

```
(node:43585) UnhandledPromiseRejectionWarning: TypeError: profiles.push is not a function
    at Object.addProfile (/usr/local/opt/nvm/versions/node/v10.7.0/lib/node_modules/@twilio/autopilot-cli/lib/json_utility.js:28:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:43585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:43585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Inspecting `~/.twilio/config.json` I could see that the account sid was saved, but not the auth token:

```json
{"projects":[{"id":"default","accountSid":"MY_ACCOUNT_SID"}]}
```

I expected `ta init` to complete without error and to populate my auth token to `~/.twilio/config.json`.

**Comment by philnash** [comment]
**Update:**

Removing `~/.twilio` and running `ta init` again succeeded. Which gave me a hint.

This tool's `init` script is not compatible with [twilio-cli](https://github.com/twilio/twilio-cli)'s `login` command. Both attempt to use `~/.twilio/config.json` but store the result in different formats.

**Comment by elizabethsiegle** [comment]
I was getting the same error and this was the fix I've been looking for! Thanks, @philnash :D

**Comment by pranavdesh** [comment]
This issue was fixed by changing the file name used by twilio-cli to store credentials.
