### ISSUE TITLE
`twilio autopilot:update` does not return proper exit code

### ISSUE THREAD

**Issue by mpmenne** [twilio/autopilot-cli#39]
There seems to be an issue with the exit code that the `twilio autopilot:update` command is returning.  I've detailed the steps to reproduce below.  At the moment I am unable to get the script to return a `1` when an error is thrown.  This bug is a blocker to using this CLI for any type of automation.

**Steps to Reproduce**
1.  Run the following commands:
```
twilio autopilot:update --schema non_existent_schema
echo $?
```

**Actual Result**
`0`

**Expected Result**
`1`

**Comment by adamchasetaylor** [comment]
@mpmenne - Did you mean to open this against the Autopilot Plugin for Twilio CLI instead? https://github.com/dabblelab/twilio-cli-autopilot-plugin

**Comment by mpmenne** [comment]
Yep!  Thanks!
